//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_Cient.FeesServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fees", Namespace="http://schemas.datacontract.org/2004/07/HM_Service")]
    [System.SerializableAttribute()]
    public partial class Fees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FeesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaidAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeesId {
            get {
                return this.FeesIdField;
            }
            set {
                if ((this.FeesIdField.Equals(value) != true)) {
                    this.FeesIdField = value;
                    this.RaisePropertyChanged("FeesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaidAmount {
            get {
                return this.PaidAmountField;
            }
            set {
                if ((this.PaidAmountField.Equals(value) != true)) {
                    this.PaidAmountField = value;
                    this.RaisePropertyChanged("PaidAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FeesServiceReference.IFeesService")]
    public interface IFeesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/GetAllFees", ReplyAction="http://tempuri.org/IFeesService/GetAllFeesResponse")]
        System.Data.DataSet GetAllFees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/GetAllFees", ReplyAction="http://tempuri.org/IFeesService/GetAllFeesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllFeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/StudentAllFees", ReplyAction="http://tempuri.org/IFeesService/StudentAllFeesResponse")]
        System.Data.DataSet StudentAllFees(int s_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/StudentAllFees", ReplyAction="http://tempuri.org/IFeesService/StudentAllFeesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> StudentAllFeesAsync(int s_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/AddFees", ReplyAction="http://tempuri.org/IFeesService/AddFeesResponse")]
        int AddFees(HM_Cient.FeesServiceReference.Fees fee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/AddFees", ReplyAction="http://tempuri.org/IFeesService/AddFeesResponse")]
        System.Threading.Tasks.Task<int> AddFeesAsync(HM_Cient.FeesServiceReference.Fees fee);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeesServiceChannel : HM_Cient.FeesServiceReference.IFeesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeesServiceClient : System.ServiceModel.ClientBase<HM_Cient.FeesServiceReference.IFeesService>, HM_Cient.FeesServiceReference.IFeesService {
        
        public FeesServiceClient() {
        }
        
        public FeesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllFees() {
            return base.Channel.GetAllFees();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllFeesAsync() {
            return base.Channel.GetAllFeesAsync();
        }
        
        public System.Data.DataSet StudentAllFees(int s_id) {
            return base.Channel.StudentAllFees(s_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> StudentAllFeesAsync(int s_id) {
            return base.Channel.StudentAllFeesAsync(s_id);
        }
        
        public int AddFees(HM_Cient.FeesServiceReference.Fees fee) {
            return base.Channel.AddFees(fee);
        }
        
        public System.Threading.Tasks.Task<int> AddFeesAsync(HM_Cient.FeesServiceReference.Fees fee) {
            return base.Channel.AddFeesAsync(fee);
        }
    }
}
