//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_Cient.StudentServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fees", Namespace="http://schemas.datacontract.org/2004/07/HM_Service")]
    [System.SerializableAttribute()]
    public partial class Fees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FeesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaidAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeesId {
            get {
                return this.FeesIdField;
            }
            set {
                if ((this.FeesIdField.Equals(value) != true)) {
                    this.FeesIdField = value;
                    this.RaisePropertyChanged("FeesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaidAmount {
            get {
                return this.PaidAmountField;
            }
            set {
                if ((this.PaidAmountField.Equals(value) != true)) {
                    this.PaidAmountField = value;
                    this.RaisePropertyChanged("PaidAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/HM_Service")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfJoiningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfJoining {
            get {
                return this.DateOfJoiningField;
            }
            set {
                if ((this.DateOfJoiningField.Equals(value) != true)) {
                    this.DateOfJoiningField = value;
                    this.RaisePropertyChanged("DateOfJoining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoomID {
            get {
                return this.RoomIDField;
            }
            set {
                if ((this.RoomIDField.Equals(value) != true)) {
                    this.RoomIDField = value;
                    this.RaisePropertyChanged("RoomID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentServiceReference.IFeesService")]
    public interface IFeesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/GetAllFees", ReplyAction="http://tempuri.org/IFeesService/GetAllFeesResponse")]
        System.Data.DataSet GetAllFees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/GetAllFees", ReplyAction="http://tempuri.org/IFeesService/GetAllFeesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllFeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/StudentAllFees", ReplyAction="http://tempuri.org/IFeesService/StudentAllFeesResponse")]
        System.Data.DataSet StudentAllFees(int s_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/StudentAllFees", ReplyAction="http://tempuri.org/IFeesService/StudentAllFeesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> StudentAllFeesAsync(int s_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/AddFees", ReplyAction="http://tempuri.org/IFeesService/AddFeesResponse")]
        int AddFees(HM_Cient.StudentServiceReference.Fees fee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/AddFees", ReplyAction="http://tempuri.org/IFeesService/AddFeesResponse")]
        System.Threading.Tasks.Task<int> AddFeesAsync(HM_Cient.StudentServiceReference.Fees fee);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeesServiceChannel : HM_Cient.StudentServiceReference.IFeesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeesServiceClient : System.ServiceModel.ClientBase<HM_Cient.StudentServiceReference.IFeesService>, HM_Cient.StudentServiceReference.IFeesService {
        
        public FeesServiceClient() {
        }
        
        public FeesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllFees() {
            return base.Channel.GetAllFees();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllFeesAsync() {
            return base.Channel.GetAllFeesAsync();
        }
        
        public System.Data.DataSet StudentAllFees(int s_id) {
            return base.Channel.StudentAllFees(s_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> StudentAllFeesAsync(int s_id) {
            return base.Channel.StudentAllFeesAsync(s_id);
        }
        
        public int AddFees(HM_Cient.StudentServiceReference.Fees fee) {
            return base.Channel.AddFees(fee);
        }
        
        public System.Threading.Tasks.Task<int> AddFeesAsync(HM_Cient.StudentServiceReference.Fees fee) {
            return base.Channel.AddFeesAsync(fee);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentServiceReference.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetAllStudents", ReplyAction="http://tempuri.org/IStudentService/GetAllStudentsResponse")]
        System.Data.DataSet GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetAllStudents", ReplyAction="http://tempuri.org/IStudentService/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
        HM_Cient.StudentServiceReference.Student GetStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
        System.Threading.Tasks.Task<HM_Cient.StudentServiceReference.Student> GetStudentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/AddStudent", ReplyAction="http://tempuri.org/IStudentService/AddStudentResponse")]
        int AddStudent(HM_Cient.StudentServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/AddStudent", ReplyAction="http://tempuri.org/IStudentService/AddStudentResponse")]
        System.Threading.Tasks.Task<int> AddStudentAsync(HM_Cient.StudentServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/UpdateStudent", ReplyAction="http://tempuri.org/IStudentService/UpdateStudentResponse")]
        int UpdateStudent(HM_Cient.StudentServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/UpdateStudent", ReplyAction="http://tempuri.org/IStudentService/UpdateStudentResponse")]
        System.Threading.Tasks.Task<int> UpdateStudentAsync(HM_Cient.StudentServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/DeleteStudent", ReplyAction="http://tempuri.org/IStudentService/DeleteStudentResponse")]
        int DeleteStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/DeleteStudent", ReplyAction="http://tempuri.org/IStudentService/DeleteStudentResponse")]
        System.Threading.Tasks.Task<int> DeleteStudentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/PendingFees", ReplyAction="http://tempuri.org/IStudentService/PendingFeesResponse")]
        int PendingFees(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/PendingFees", ReplyAction="http://tempuri.org/IStudentService/PendingFeesResponse")]
        System.Threading.Tasks.Task<int> PendingFeesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/NoOfStudents", ReplyAction="http://tempuri.org/IStudentService/NoOfStudentsResponse")]
        int NoOfStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/NoOfStudents", ReplyAction="http://tempuri.org/IStudentService/NoOfStudentsResponse")]
        System.Threading.Tasks.Task<int> NoOfStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CountStudentsWithPendingFees", ReplyAction="http://tempuri.org/IStudentService/CountStudentsWithPendingFeesResponse")]
        int CountStudentsWithPendingFees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CountStudentsWithPendingFees", ReplyAction="http://tempuri.org/IStudentService/CountStudentsWithPendingFeesResponse")]
        System.Threading.Tasks.Task<int> CountStudentsWithPendingFeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentsByFirstName", ReplyAction="http://tempuri.org/IStudentService/GetStudentsByFirstNameResponse")]
        System.Data.DataSet GetStudentsByFirstName(string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentsByFirstName", ReplyAction="http://tempuri.org/IStudentService/GetStudentsByFirstNameResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStudentsByFirstNameAsync(string firstName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : HM_Cient.StudentServiceReference.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<HM_Cient.StudentServiceReference.IStudentService>, HM_Cient.StudentServiceReference.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        public HM_Cient.StudentServiceReference.Student GetStudent(int id) {
            return base.Channel.GetStudent(id);
        }
        
        public System.Threading.Tasks.Task<HM_Cient.StudentServiceReference.Student> GetStudentAsync(int id) {
            return base.Channel.GetStudentAsync(id);
        }
        
        public int AddStudent(HM_Cient.StudentServiceReference.Student student) {
            return base.Channel.AddStudent(student);
        }
        
        public System.Threading.Tasks.Task<int> AddStudentAsync(HM_Cient.StudentServiceReference.Student student) {
            return base.Channel.AddStudentAsync(student);
        }
        
        public int UpdateStudent(HM_Cient.StudentServiceReference.Student student) {
            return base.Channel.UpdateStudent(student);
        }
        
        public System.Threading.Tasks.Task<int> UpdateStudentAsync(HM_Cient.StudentServiceReference.Student student) {
            return base.Channel.UpdateStudentAsync(student);
        }
        
        public int DeleteStudent(int id) {
            return base.Channel.DeleteStudent(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteStudentAsync(int id) {
            return base.Channel.DeleteStudentAsync(id);
        }
        
        public int PendingFees(int id) {
            return base.Channel.PendingFees(id);
        }
        
        public System.Threading.Tasks.Task<int> PendingFeesAsync(int id) {
            return base.Channel.PendingFeesAsync(id);
        }
        
        public int NoOfStudents() {
            return base.Channel.NoOfStudents();
        }
        
        public System.Threading.Tasks.Task<int> NoOfStudentsAsync() {
            return base.Channel.NoOfStudentsAsync();
        }
        
        public int CountStudentsWithPendingFees() {
            return base.Channel.CountStudentsWithPendingFees();
        }
        
        public System.Threading.Tasks.Task<int> CountStudentsWithPendingFeesAsync() {
            return base.Channel.CountStudentsWithPendingFeesAsync();
        }
        
        public System.Data.DataSet GetStudentsByFirstName(string firstName) {
            return base.Channel.GetStudentsByFirstName(firstName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStudentsByFirstNameAsync(string firstName) {
            return base.Channel.GetStudentsByFirstNameAsync(firstName);
        }
    }
}
