//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_Cient.RoomServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/HM_Service")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfJoiningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfJoining {
            get {
                return this.DateOfJoiningField;
            }
            set {
                if ((this.DateOfJoiningField.Equals(value) != true)) {
                    this.DateOfJoiningField = value;
                    this.RaisePropertyChanged("DateOfJoining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoomID {
            get {
                return this.RoomIDField;
            }
            set {
                if ((this.RoomIDField.Equals(value) != true)) {
                    this.RoomIDField = value;
                    this.RaisePropertyChanged("RoomID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/HM_Service")]
    [System.SerializableAttribute()]
    public partial class Staff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfJoiningField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StaffIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfJoining {
            get {
                return this.DateOfJoiningField;
            }
            set {
                if ((this.DateOfJoiningField.Equals(value) != true)) {
                    this.DateOfJoiningField = value;
                    this.RaisePropertyChanged("DateOfJoining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StaffId {
            get {
                return this.StaffIdField;
            }
            set {
                if ((this.StaffIdField.Equals(value) != true)) {
                    this.StaffIdField = value;
                    this.RaisePropertyChanged("StaffId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkType {
            get {
                return this.WorkTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkTypeField, value) != true)) {
                    this.WorkTypeField = value;
                    this.RaisePropertyChanged("WorkType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fees", Namespace="http://schemas.datacontract.org/2004/07/HM_Service")]
    [System.SerializableAttribute()]
    public partial class Fees : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FeesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaidAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PaymentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeesId {
            get {
                return this.FeesIdField;
            }
            set {
                if ((this.FeesIdField.Equals(value) != true)) {
                    this.FeesIdField = value;
                    this.RaisePropertyChanged("FeesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaidAmount {
            get {
                return this.PaidAmountField;
            }
            set {
                if ((this.PaidAmountField.Equals(value) != true)) {
                    this.PaidAmountField = value;
                    this.RaisePropertyChanged("PaidAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://schemas.datacontract.org/2004/07/HM_Service")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BedVacancyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BedVacancy {
            get {
                return this.BedVacancyField;
            }
            set {
                if ((this.BedVacancyField.Equals(value) != true)) {
                    this.BedVacancyField = value;
                    this.RaisePropertyChanged("BedVacancy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((this.RoomIdField.Equals(value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomType {
            get {
                return this.RoomTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomTypeField, value) != true)) {
                    this.RoomTypeField = value;
                    this.RaisePropertyChanged("RoomType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomServiceReference.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetAllStudents", ReplyAction="http://tempuri.org/IStudentService/GetAllStudentsResponse")]
        System.Data.DataSet GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetAllStudents", ReplyAction="http://tempuri.org/IStudentService/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
        HM_Cient.RoomServiceReference.Student GetStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
        System.Threading.Tasks.Task<HM_Cient.RoomServiceReference.Student> GetStudentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/AddStudent", ReplyAction="http://tempuri.org/IStudentService/AddStudentResponse")]
        int AddStudent(HM_Cient.RoomServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/AddStudent", ReplyAction="http://tempuri.org/IStudentService/AddStudentResponse")]
        System.Threading.Tasks.Task<int> AddStudentAsync(HM_Cient.RoomServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/UpdateStudent", ReplyAction="http://tempuri.org/IStudentService/UpdateStudentResponse")]
        int UpdateStudent(HM_Cient.RoomServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/UpdateStudent", ReplyAction="http://tempuri.org/IStudentService/UpdateStudentResponse")]
        System.Threading.Tasks.Task<int> UpdateStudentAsync(HM_Cient.RoomServiceReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/DeleteStudent", ReplyAction="http://tempuri.org/IStudentService/DeleteStudentResponse")]
        int DeleteStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/DeleteStudent", ReplyAction="http://tempuri.org/IStudentService/DeleteStudentResponse")]
        System.Threading.Tasks.Task<int> DeleteStudentAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/PendingFees", ReplyAction="http://tempuri.org/IStudentService/PendingFeesResponse")]
        int PendingFees(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/PendingFees", ReplyAction="http://tempuri.org/IStudentService/PendingFeesResponse")]
        System.Threading.Tasks.Task<int> PendingFeesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/NoOfStudents", ReplyAction="http://tempuri.org/IStudentService/NoOfStudentsResponse")]
        int NoOfStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/NoOfStudents", ReplyAction="http://tempuri.org/IStudentService/NoOfStudentsResponse")]
        System.Threading.Tasks.Task<int> NoOfStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CountStudentsWithPendingFees", ReplyAction="http://tempuri.org/IStudentService/CountStudentsWithPendingFeesResponse")]
        int CountStudentsWithPendingFees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CountStudentsWithPendingFees", ReplyAction="http://tempuri.org/IStudentService/CountStudentsWithPendingFeesResponse")]
        System.Threading.Tasks.Task<int> CountStudentsWithPendingFeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentsByFirstName", ReplyAction="http://tempuri.org/IStudentService/GetStudentsByFirstNameResponse")]
        System.Data.DataSet GetStudentsByFirstName(string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentsByFirstName", ReplyAction="http://tempuri.org/IStudentService/GetStudentsByFirstNameResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStudentsByFirstNameAsync(string firstName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : HM_Cient.RoomServiceReference.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<HM_Cient.RoomServiceReference.IStudentService>, HM_Cient.RoomServiceReference.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        public HM_Cient.RoomServiceReference.Student GetStudent(int id) {
            return base.Channel.GetStudent(id);
        }
        
        public System.Threading.Tasks.Task<HM_Cient.RoomServiceReference.Student> GetStudentAsync(int id) {
            return base.Channel.GetStudentAsync(id);
        }
        
        public int AddStudent(HM_Cient.RoomServiceReference.Student student) {
            return base.Channel.AddStudent(student);
        }
        
        public System.Threading.Tasks.Task<int> AddStudentAsync(HM_Cient.RoomServiceReference.Student student) {
            return base.Channel.AddStudentAsync(student);
        }
        
        public int UpdateStudent(HM_Cient.RoomServiceReference.Student student) {
            return base.Channel.UpdateStudent(student);
        }
        
        public System.Threading.Tasks.Task<int> UpdateStudentAsync(HM_Cient.RoomServiceReference.Student student) {
            return base.Channel.UpdateStudentAsync(student);
        }
        
        public int DeleteStudent(int id) {
            return base.Channel.DeleteStudent(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteStudentAsync(int id) {
            return base.Channel.DeleteStudentAsync(id);
        }
        
        public int PendingFees(int id) {
            return base.Channel.PendingFees(id);
        }
        
        public System.Threading.Tasks.Task<int> PendingFeesAsync(int id) {
            return base.Channel.PendingFeesAsync(id);
        }
        
        public int NoOfStudents() {
            return base.Channel.NoOfStudents();
        }
        
        public System.Threading.Tasks.Task<int> NoOfStudentsAsync() {
            return base.Channel.NoOfStudentsAsync();
        }
        
        public int CountStudentsWithPendingFees() {
            return base.Channel.CountStudentsWithPendingFees();
        }
        
        public System.Threading.Tasks.Task<int> CountStudentsWithPendingFeesAsync() {
            return base.Channel.CountStudentsWithPendingFeesAsync();
        }
        
        public System.Data.DataSet GetStudentsByFirstName(string firstName) {
            return base.Channel.GetStudentsByFirstName(firstName);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStudentsByFirstNameAsync(string firstName) {
            return base.Channel.GetStudentsByFirstNameAsync(firstName);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomServiceReference.IStaffService")]
    public interface IStaffService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/GetAllStaffs", ReplyAction="http://tempuri.org/IStaffService/GetAllStaffsResponse")]
        System.Data.DataSet GetAllStaffs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/GetAllStaffs", ReplyAction="http://tempuri.org/IStaffService/GetAllStaffsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllStaffsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/GetStaff", ReplyAction="http://tempuri.org/IStaffService/GetStaffResponse")]
        HM_Cient.RoomServiceReference.Staff GetStaff(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/GetStaff", ReplyAction="http://tempuri.org/IStaffService/GetStaffResponse")]
        System.Threading.Tasks.Task<HM_Cient.RoomServiceReference.Staff> GetStaffAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/AddStaff", ReplyAction="http://tempuri.org/IStaffService/AddStaffResponse")]
        int AddStaff(HM_Cient.RoomServiceReference.Staff staff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/AddStaff", ReplyAction="http://tempuri.org/IStaffService/AddStaffResponse")]
        System.Threading.Tasks.Task<int> AddStaffAsync(HM_Cient.RoomServiceReference.Staff staff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/DeleteStaff", ReplyAction="http://tempuri.org/IStaffService/DeleteStaffResponse")]
        int DeleteStaff(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/DeleteStaff", ReplyAction="http://tempuri.org/IStaffService/DeleteStaffResponse")]
        System.Threading.Tasks.Task<int> DeleteStaffAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/UpdateStaff", ReplyAction="http://tempuri.org/IStaffService/UpdateStaffResponse")]
        int UpdateStaff(HM_Cient.RoomServiceReference.Staff staff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/UpdateStaff", ReplyAction="http://tempuri.org/IStaffService/UpdateStaffResponse")]
        System.Threading.Tasks.Task<int> UpdateStaffAsync(HM_Cient.RoomServiceReference.Staff staff);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/NoOfStaffs", ReplyAction="http://tempuri.org/IStaffService/NoOfStaffsResponse")]
        int NoOfStaffs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStaffService/NoOfStaffs", ReplyAction="http://tempuri.org/IStaffService/NoOfStaffsResponse")]
        System.Threading.Tasks.Task<int> NoOfStaffsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStaffServiceChannel : HM_Cient.RoomServiceReference.IStaffService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StaffServiceClient : System.ServiceModel.ClientBase<HM_Cient.RoomServiceReference.IStaffService>, HM_Cient.RoomServiceReference.IStaffService {
        
        public StaffServiceClient() {
        }
        
        public StaffServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StaffServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StaffServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllStaffs() {
            return base.Channel.GetAllStaffs();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllStaffsAsync() {
            return base.Channel.GetAllStaffsAsync();
        }
        
        public HM_Cient.RoomServiceReference.Staff GetStaff(int id) {
            return base.Channel.GetStaff(id);
        }
        
        public System.Threading.Tasks.Task<HM_Cient.RoomServiceReference.Staff> GetStaffAsync(int id) {
            return base.Channel.GetStaffAsync(id);
        }
        
        public int AddStaff(HM_Cient.RoomServiceReference.Staff staff) {
            return base.Channel.AddStaff(staff);
        }
        
        public System.Threading.Tasks.Task<int> AddStaffAsync(HM_Cient.RoomServiceReference.Staff staff) {
            return base.Channel.AddStaffAsync(staff);
        }
        
        public int DeleteStaff(int id) {
            return base.Channel.DeleteStaff(id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteStaffAsync(int id) {
            return base.Channel.DeleteStaffAsync(id);
        }
        
        public int UpdateStaff(HM_Cient.RoomServiceReference.Staff staff) {
            return base.Channel.UpdateStaff(staff);
        }
        
        public System.Threading.Tasks.Task<int> UpdateStaffAsync(HM_Cient.RoomServiceReference.Staff staff) {
            return base.Channel.UpdateStaffAsync(staff);
        }
        
        public int NoOfStaffs() {
            return base.Channel.NoOfStaffs();
        }
        
        public System.Threading.Tasks.Task<int> NoOfStaffsAsync() {
            return base.Channel.NoOfStaffsAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomServiceReference.IFeesService")]
    public interface IFeesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/GetAllFees", ReplyAction="http://tempuri.org/IFeesService/GetAllFeesResponse")]
        System.Data.DataSet GetAllFees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/GetAllFees", ReplyAction="http://tempuri.org/IFeesService/GetAllFeesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllFeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/StudentAllFees", ReplyAction="http://tempuri.org/IFeesService/StudentAllFeesResponse")]
        System.Data.DataSet StudentAllFees(int s_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/StudentAllFees", ReplyAction="http://tempuri.org/IFeesService/StudentAllFeesResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> StudentAllFeesAsync(int s_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/AddFees", ReplyAction="http://tempuri.org/IFeesService/AddFeesResponse")]
        int AddFees(HM_Cient.RoomServiceReference.Fees fee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeesService/AddFees", ReplyAction="http://tempuri.org/IFeesService/AddFeesResponse")]
        System.Threading.Tasks.Task<int> AddFeesAsync(HM_Cient.RoomServiceReference.Fees fee);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeesServiceChannel : HM_Cient.RoomServiceReference.IFeesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeesServiceClient : System.ServiceModel.ClientBase<HM_Cient.RoomServiceReference.IFeesService>, HM_Cient.RoomServiceReference.IFeesService {
        
        public FeesServiceClient() {
        }
        
        public FeesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllFees() {
            return base.Channel.GetAllFees();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllFeesAsync() {
            return base.Channel.GetAllFeesAsync();
        }
        
        public System.Data.DataSet StudentAllFees(int s_id) {
            return base.Channel.StudentAllFees(s_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> StudentAllFeesAsync(int s_id) {
            return base.Channel.StudentAllFeesAsync(s_id);
        }
        
        public int AddFees(HM_Cient.RoomServiceReference.Fees fee) {
            return base.Channel.AddFees(fee);
        }
        
        public System.Threading.Tasks.Task<int> AddFeesAsync(HM_Cient.RoomServiceReference.Fees fee) {
            return base.Channel.AddFeesAsync(fee);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomServiceReference.IRoomService")]
    public interface IRoomService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetAllRooms", ReplyAction="http://tempuri.org/IRoomService/GetAllRoomsResponse")]
        System.Data.DataSet GetAllRooms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetAllRooms", ReplyAction="http://tempuri.org/IRoomService/GetAllRoomsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllRoomsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetRoom", ReplyAction="http://tempuri.org/IRoomService/GetRoomResponse")]
        HM_Cient.RoomServiceReference.Room GetRoom(int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetRoom", ReplyAction="http://tempuri.org/IRoomService/GetRoomResponse")]
        System.Threading.Tasks.Task<HM_Cient.RoomServiceReference.Room> GetRoomAsync(int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/AddRoom", ReplyAction="http://tempuri.org/IRoomService/AddRoomResponse")]
        int AddRoom(HM_Cient.RoomServiceReference.Room room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/AddRoom", ReplyAction="http://tempuri.org/IRoomService/AddRoomResponse")]
        System.Threading.Tasks.Task<int> AddRoomAsync(HM_Cient.RoomServiceReference.Room room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/UpdateRoom", ReplyAction="http://tempuri.org/IRoomService/UpdateRoomResponse")]
        int UpdateRoom(HM_Cient.RoomServiceReference.Room room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/UpdateRoom", ReplyAction="http://tempuri.org/IRoomService/UpdateRoomResponse")]
        System.Threading.Tasks.Task<int> UpdateRoomAsync(HM_Cient.RoomServiceReference.Room room);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/DeleteRoom", ReplyAction="http://tempuri.org/IRoomService/DeleteRoomResponse")]
        int DeleteRoom(int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/DeleteRoom", ReplyAction="http://tempuri.org/IRoomService/DeleteRoomResponse")]
        System.Threading.Tasks.Task<int> DeleteRoomAsync(int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetVacantRoomIds", ReplyAction="http://tempuri.org/IRoomService/GetVacantRoomIdsResponse")]
        int[] GetVacantRoomIds();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetVacantRoomIds", ReplyAction="http://tempuri.org/IRoomService/GetVacantRoomIdsResponse")]
        System.Threading.Tasks.Task<int[]> GetVacantRoomIdsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetVacantRoomIdsWithAC", ReplyAction="http://tempuri.org/IRoomService/GetVacantRoomIdsWithACResponse")]
        int[] GetVacantRoomIdsWithAC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetVacantRoomIdsWithAC", ReplyAction="http://tempuri.org/IRoomService/GetVacantRoomIdsWithACResponse")]
        System.Threading.Tasks.Task<int[]> GetVacantRoomIdsWithACAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetVacantRoomIdsWithNonAC", ReplyAction="http://tempuri.org/IRoomService/GetVacantRoomIdsWithNonACResponse")]
        int[] GetVacantRoomIdsWithNonAC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetVacantRoomIdsWithNonAC", ReplyAction="http://tempuri.org/IRoomService/GetVacantRoomIdsWithNonACResponse")]
        System.Threading.Tasks.Task<int[]> GetVacantRoomIdsWithNonACAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/NoOfRooms", ReplyAction="http://tempuri.org/IRoomService/NoOfRoomsResponse")]
        int NoOfRooms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/NoOfRooms", ReplyAction="http://tempuri.org/IRoomService/NoOfRoomsResponse")]
        System.Threading.Tasks.Task<int> NoOfRoomsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetTotalVacantRooms", ReplyAction="http://tempuri.org/IRoomService/GetTotalVacantRoomsResponse")]
        int GetTotalVacantRooms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetTotalVacantRooms", ReplyAction="http://tempuri.org/IRoomService/GetTotalVacantRoomsResponse")]
        System.Threading.Tasks.Task<int> GetTotalVacantRoomsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetStudentsInRoom", ReplyAction="http://tempuri.org/IRoomService/GetStudentsInRoomResponse")]
        string[] GetStudentsInRoom(int room_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomService/GetStudentsInRoom", ReplyAction="http://tempuri.org/IRoomService/GetStudentsInRoomResponse")]
        System.Threading.Tasks.Task<string[]> GetStudentsInRoomAsync(int room_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomServiceChannel : HM_Cient.RoomServiceReference.IRoomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomServiceClient : System.ServiceModel.ClientBase<HM_Cient.RoomServiceReference.IRoomService>, HM_Cient.RoomServiceReference.IRoomService {
        
        public RoomServiceClient() {
        }
        
        public RoomServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoomServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllRooms() {
            return base.Channel.GetAllRooms();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllRoomsAsync() {
            return base.Channel.GetAllRoomsAsync();
        }
        
        public HM_Cient.RoomServiceReference.Room GetRoom(int room_id) {
            return base.Channel.GetRoom(room_id);
        }
        
        public System.Threading.Tasks.Task<HM_Cient.RoomServiceReference.Room> GetRoomAsync(int room_id) {
            return base.Channel.GetRoomAsync(room_id);
        }
        
        public int AddRoom(HM_Cient.RoomServiceReference.Room room) {
            return base.Channel.AddRoom(room);
        }
        
        public System.Threading.Tasks.Task<int> AddRoomAsync(HM_Cient.RoomServiceReference.Room room) {
            return base.Channel.AddRoomAsync(room);
        }
        
        public int UpdateRoom(HM_Cient.RoomServiceReference.Room room) {
            return base.Channel.UpdateRoom(room);
        }
        
        public System.Threading.Tasks.Task<int> UpdateRoomAsync(HM_Cient.RoomServiceReference.Room room) {
            return base.Channel.UpdateRoomAsync(room);
        }
        
        public int DeleteRoom(int room_id) {
            return base.Channel.DeleteRoom(room_id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteRoomAsync(int room_id) {
            return base.Channel.DeleteRoomAsync(room_id);
        }
        
        public int[] GetVacantRoomIds() {
            return base.Channel.GetVacantRoomIds();
        }
        
        public System.Threading.Tasks.Task<int[]> GetVacantRoomIdsAsync() {
            return base.Channel.GetVacantRoomIdsAsync();
        }
        
        public int[] GetVacantRoomIdsWithAC() {
            return base.Channel.GetVacantRoomIdsWithAC();
        }
        
        public System.Threading.Tasks.Task<int[]> GetVacantRoomIdsWithACAsync() {
            return base.Channel.GetVacantRoomIdsWithACAsync();
        }
        
        public int[] GetVacantRoomIdsWithNonAC() {
            return base.Channel.GetVacantRoomIdsWithNonAC();
        }
        
        public System.Threading.Tasks.Task<int[]> GetVacantRoomIdsWithNonACAsync() {
            return base.Channel.GetVacantRoomIdsWithNonACAsync();
        }
        
        public int NoOfRooms() {
            return base.Channel.NoOfRooms();
        }
        
        public System.Threading.Tasks.Task<int> NoOfRoomsAsync() {
            return base.Channel.NoOfRoomsAsync();
        }
        
        public int GetTotalVacantRooms() {
            return base.Channel.GetTotalVacantRooms();
        }
        
        public System.Threading.Tasks.Task<int> GetTotalVacantRoomsAsync() {
            return base.Channel.GetTotalVacantRoomsAsync();
        }
        
        public string[] GetStudentsInRoom(int room_id) {
            return base.Channel.GetStudentsInRoom(room_id);
        }
        
        public System.Threading.Tasks.Task<string[]> GetStudentsInRoomAsync(int room_id) {
            return base.Channel.GetStudentsInRoomAsync(room_id);
        }
    }
}
